"""Run the active run scripts generated by step 0 against a real browser.

Reads the active run from ``active_run.yaml``, finds the most recently
generated scripts in the ``scripts/`` directory, and executes them as
standalone subprocesses against a live Chromium instance. Step 0 emits
up to TWO scripts per run: an optional discovery script
(``<date>__discover__<slug>.py``) that collects link URLs into the
``discovered_links`` table, and the processing script
(``<date>__<slug>.py``) that reads that table and extracts metadata +
downloads files. This driver runs them in order — discovery first
(populating ``discovered_links``), then processing (consuming it).
Each script is self-contained (all vendored helpers prepended at emit
time) and uses ``__file__`` to resolve its metadata database path, so
running it directly with ``python`` writes into the run's
``metadata.db``.

Usage:
    python -m browser_agent.drivers.step_1_run_active_scraper
"""

from __future__ import annotations

import asyncio
import os
import re
import signal
import sys
import time
from pathlib import Path

from loguru import logger

from browser_agent.adapters.runs_config_loader import RunsConfigLoader
from browser_agent.configuration import ZENDRIVER_HEADLESS
from browser_agent.logging_config import configure_logging

# How long (seconds) to let the scraper run before killing it.
# Default to 6 hours — a full multi-document scrape can take a long
# time. Override with the ``SCRAPER_RUN_TIMEOUT_S`` env variable.
_RUN_TIMEOUT_S = int(os.environ.get("SCRAPER_RUN_TIMEOUT_S", str(6 * 3600)))

# Exit code returned when the active script path cannot be resolved.
_EXIT_NO_SCRIPT = 2

# Filename token that marks a discovery script emitted by step 0.
# Used to split the scripts/ directory into the discovery script and
# the processing script.
_DISCOVER_TOKEN = "__discover"


class RunActiveScraperDriver:
    """End-to-end driver: locate the active script and execute it."""

    def run(self) -> int:
        """Configure logging, run the async pipeline, return the exit code."""
        configure_logging()
        return asyncio.run(self._run_async())

    async def _run_async(self) -> int:
        """Load the active run, run discovery (if present) then the processing script."""
        run = RunsConfigLoader.load_active()
        run_path = RunsConfigLoader.resolve_active_path()
        logger.info("step 1 (run active scraper) starting run={run}", run=run.name)

        processing_path = self._latest_script_path(run_path, kind="processing")
        if processing_path is None:
            return _EXIT_NO_SCRIPT

        await self._run_discovery_step(run_path)

        logger.info("running processing script {path}", path=processing_path)
        t0 = time.monotonic()
        exit_code = await self._run_script(processing_path)
        elapsed = time.monotonic() - t0
        logger.info(
            "processing script finished in {elapsed:.1f}s (exit code {code})",
            elapsed=elapsed,
            code=exit_code,
        )
        return exit_code

    async def _run_discovery_step(self, run_path: Path) -> None:
        """Run the discovery script if present (best-effort, populates discovered_links)."""
        discovery_path = self._latest_script_path(run_path, kind="discovery")
        if discovery_path is None:
            logger.warning("no discovery script found — proceeding to processing")
            return
        logger.info("running discovery script {path}", path=discovery_path)
        t0 = time.monotonic()
        exit_code = await self._run_script(discovery_path)
        elapsed = time.monotonic() - t0
        logger.info(
            "discovery script finished in {elapsed:.1f}s (exit code {code})",
            elapsed=elapsed,
            code=exit_code,
        )

    def _latest_script_path(self, run_path: Path, *, kind: str) -> Path | None:
        """Return the most recent ``scripts/*.py`` matching the kind, or None.

        ``kind="discovery"`` selects ``<date>__discover__*.py``;
        ``kind="processing"`` selects ``<date>__<slug>.py`` (everything
        dated ``YYYY_MM_DD`` excluding ``__discover`` and ``.raw.py``).
        """
        scripts_dir = run_path / "scripts"
        if not scripts_dir.is_dir():
            logger.warning("no scripts directory at {dir}", dir=scripts_dir)
            return None
        scripts = sorted(
            p
            for p in scripts_dir.glob("*.py")
            if re.match(r"\d{4}_\d{2}_\d{2}", p.name)
            and not p.name.endswith(".raw.py")
            and (_DISCOVER_TOKEN in p.name) == (kind == "discovery")
        )
        if not scripts:
            logger.warning(
                "no {kind} scripts found in {dir}",
                kind=kind,
                dir=scripts_dir,
            )
            return None
        return scripts[-1]

    async def _run_script(self, script_path: Path) -> int:
        """Execute ``script_path`` as a subprocess with the project Python.

        Returns the script's exit code. The script runs with a long
        timeout (default 6 hours) to accommodate full multi-document
        scrapes.  Output is streamed line-by-line to stdout in real
        time so the operator can monitor progress.
        """
        headless = "true" if ZENDRIVER_HEADLESS else "false"
        env = {
            **os.environ,
            "PYTHONUNBUFFERED": "1",
            "ZENDRIVER_HEADLESS": headless,
        }
        cmd = [sys.executable, str(script_path)]

        try:
            proc = await asyncio.create_subprocess_exec(
                *cmd,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.STDOUT,
                start_new_session=True,
                env=env,
            )
        except OSError as exc:
            logger.error("failed to launch scraper subprocess: {exc}", exc=exc)
            return _EXIT_NO_SCRIPT

        try:
            await asyncio.wait_for(
                self._stream_output(proc),
                timeout=_RUN_TIMEOUT_S,
            )
        except asyncio.TimeoutError:
            await self._kill_process_group(proc)
            logger.error(
                "scraper timed out after {t}s — killed process group",
                t=_RUN_TIMEOUT_S,
            )
            return 124

        exit_code = proc.returncode if proc.returncode is not None else 1
        if exit_code == 0:
            logger.info("scraper completed successfully (exit code 0)")
        else:
            logger.error("scraper failed with exit code {code}", code=exit_code)

        return exit_code

    async def _stream_output(self, proc: asyncio.subprocess.Process) -> str:
        """Read subprocess stdout line by line, print each line to the
        terminal in real time, and return the complete output string."""
        lines: list[str] = []
        assert proc.stdout is not None
        while True:
            line = await proc.stdout.readline()
            if not line:
                break
            text = line.decode("utf-8", errors="replace")
            print(text, end="", flush=True)
            lines.append(text)
        # Process should have exited — ensure returncode is set.
        await proc.wait()
        return "".join(lines)

    @staticmethod
    async def _kill_process_group(proc: asyncio.subprocess.Process) -> None:
        """Kill the process group (Python + Chromium child) on timeout."""
        try:
            os.killpg(os.getpgid(proc.pid), signal.SIGTERM)
        except (ProcessLookupError, PermissionError):
            _ = proc.kill()
        try:
            await asyncio.wait_for(proc.wait(), timeout=5)
        except asyncio.TimeoutError:
            try:
                os.killpg(os.getpgid(proc.pid), signal.SIGKILL)
            except (ProcessLookupError, PermissionError):
                proc.kill()


def main() -> None:
    """Module entry point."""
    raise SystemExit(RunActiveScraperDriver().run())


if __name__ == "__main__":
    main()
