"""Run the active run script generated by step 0 against a real browser.

Reads the active run from ``active_run.yaml``, finds the most recently
generated script in the ``scripts/`` directory, and executes it as a
standalone subprocess against a live Chromium instance. The script is
self-contained (all vendored helpers prepended at emit time) and uses
``__file__`` to resolve its metadata database path, so running it
directly with ``python`` writes into the run's ``metadata.db``.

Usage:
    python -m browser_agent.drivers.step_1_run_active_scraper
"""

from __future__ import annotations

import asyncio
import os
import signal
import sys
from pathlib import Path

from loguru import logger

from browser_agent.adapters.runs_config_loader import RunsConfigLoader
from browser_agent.configuration import ZENDRIVER_HEADLESS
from browser_agent.logging_config import configure_logging

# How long (seconds) to let the scraper run before killing it.
# Default to 6 hours — a full multi-document scrape can take a long
# time. Override with the ``SCRAPER_RUN_TIMEOUT_S`` env variable.
_RUN_TIMEOUT_S = int(os.environ.get("SCRAPER_RUN_TIMEOUT_S", str(6 * 3600)))

# Exit code returned when the active script path cannot be resolved.
_EXIT_NO_SCRIPT = 2


class RunActiveScraperDriver:
    """End-to-end driver: locate the active script and execute it."""

    def run(self) -> int:
        """Configure logging, run the async pipeline, return the exit code."""
        configure_logging()
        return asyncio.run(self._run_async())

    async def _run_async(self) -> int:
        """Load the active run, find the latest script, and run it."""
        run = RunsConfigLoader.load_active()
        run_path = RunsConfigLoader.load_active_path()
        logger.info("step 1 (run active scraper) starting run={run}", run=run.name)

        script_path = self._latest_script_path(run_path)
        if script_path is None:
            return _EXIT_NO_SCRIPT

        logger.info("running scraper script {path}", path=script_path)
        return await self._run_script(script_path)

    def _latest_script_path(self, run_path: Path) -> Path | None:
        """Return the most recent ``scripts/*.py`` path, or None."""
        scripts_dir = run_path / "scripts"
        if not scripts_dir.is_dir():
            logger.warning("no scripts directory at {dir}", dir=scripts_dir)
            return None
        scripts = sorted(scripts_dir.glob("*.py"), key=lambda p: p.stat().st_mtime)
        if not scripts:
            logger.warning("no step 0 scripts found in {dir}", dir=scripts_dir)
            return None
        return scripts[-1]

    async def _run_script(self, script_path: Path) -> int:
        """Execute ``script_path`` as a subprocess with the project Python.

        Returns the script's exit code. The script runs with a long
        timeout (default 6 hours) to accommodate full multi-document
        scrapes.
        """
        headless = "true" if ZENDRIVER_HEADLESS else "false"
        env = {**os.environ, "ZENDRIVER_HEADLESS": headless}
        cmd = [sys.executable, str(script_path)]

        try:
            proc = await asyncio.create_subprocess_exec(
                *cmd,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.STDOUT,
                start_new_session=True,
                env=env,
            )
        except OSError as exc:
            logger.error("failed to launch scraper subprocess: {exc}", exc=exc)
            return _EXIT_NO_SCRIPT

        try:
            stdout, _ = await asyncio.wait_for(proc.communicate(), timeout=_RUN_TIMEOUT_S)
        except asyncio.TimeoutError:
            await self._kill_process_group(proc)
            logger.error(
                "scraper timed out after {t}s — killed process group",
                t=_RUN_TIMEOUT_S,
            )
            return 124

        output = stdout.decode("utf-8", errors="replace") if stdout else ""
        if output.strip():
            logger.info("scraper output:\n{output}", output=output)

        exit_code = proc.returncode if proc.returncode is not None else 1
        if exit_code == 0:
            logger.info("scraper completed successfully (exit code 0)")
        else:
            logger.error("scraper failed with exit code {code}", code=exit_code)

        return exit_code

    @staticmethod
    async def _kill_process_group(proc: asyncio.subprocess.Process) -> None:
        """Kill the process group (Python + Chromium child) on timeout."""
        try:
            os.killpg(os.getpgid(proc.pid), signal.SIGTERM)
        except (ProcessLookupError, PermissionError):
            _ = proc.kill()
        try:
            await asyncio.wait_for(proc.wait(), timeout=5)
        except asyncio.TimeoutError:
            try:
                os.killpg(os.getpgid(proc.pid), signal.SIGKILL)
            except (ProcessLookupError, PermissionError):
                proc.kill()


def main() -> None:
    """Module entry point."""
    raise SystemExit(RunActiveScraperDriver().run())


if __name__ == "__main__":
    main()
